### ISSUE TITLE
Create an R package

### ISSUE THREAD

**Issue by schnorr** [schnorr/starvz#1]
We should at some point transform StarVZ into an R package, to make it easier to use. The latest workflow has two phases: (1) _Data Processing_ and (2) _Data Visualization_. The first phase consists of a bunch of shell scripts, other computer programs such as `starpu_fxt_tool`, `pj_dump` that live better outside of the R world. My proposal is  that this first phase should be outside of the scope of the R package and should be kept as a bunch of R scripts. The second phase, however, could be packaged very easily since it is purely in R (or C++ encapsulated with Rcpp).

A initial effort has been started by @llnns in the Rpackage branch.

**Comment by llnns** [comment]
Partially done.

I merged the Rpackage and the master branch.

The new installation procedure is provided in the `INSTALL.org`

Tests should be done.

**Comment by stanisic** [comment]
Works! :)
Not so smoothly and with several minor changes and hacks though, so the final solution should be improved and made foolproof for external users, but for internal purposes the current version is already good...

**Comment by stanisic** [comment]
Just to note here that many things in installation/setup became much easier and smoother when @llnns fixed the starvz R_package installation (as discussed in Issue #2)

**Comment by stanisic** [comment]
In conclusion, R package seems to be in a good state and easy to install. I dont dare closing this issue myself, as I dont know if everyone else agrees and if someone has any additional plans regarding packaging :)
