### ISSUE TITLE
Problem with aggregating CFD data

### ISSUE THREAD

**Issue by stanisic** [schnorr/starvz#2]
When trying to aggregate data from CFD experiments, I get the following error when calling integrate.stepfunc.Rcpp(slices, breaks, values) ( [link to the code](https://github.com/schnorr/starvz/blob/99c700c2d25aedfcfbaec922a1d9440fe828dfb4/R_package/R/phase2_time_integration.R#L75)):

`
Error in .Call("_starvz_integrateStepFunc", PACKAGE = "starvz", x, bounds,  : 
  "_starvz_integrateStepFunc" not available for .Call() for package "starvz"
`

Not sure if the problem is coming from the installation/configuration, from the function itself or my input data (although inputs look fine), but I thought maybe someone else already experienced a similar issue and knows a quick fix...

**Comment by llnns** [comment]
Hi,

 There were some R package errors, commit 7163f230f8961a607818fdc3c6ff209c7db32551 should solve it. It require a uninstall:
```remove.packages("starvz")```
And a re-install:
```devtools::install_github("schnorr/starvz", subdir="R_package")```

Doing a ```st_time_aggregation(data$State)``` returns the correct values now.

Let me know if it solves the problem.

**Comment by stanisic** [comment]
Thanks, your commit indeed solved the issue and I was able to use aggregation. However, now when using it I am observing some strange results which give me doubts whether aggregation is indeed computed correctly. Or perhaps I am not using it correctly :)

Still on the CFD experiments, when trying to do the aggregation of the task durations on different parts of the matrix (specified by X and Y columns), the obtained aggregated values seem to be completely off. For a specified period of time, which is equal to the "step" (the granularity of the aggregation), aggregated data reports spending 40% or 77% in one task type, while the raw trace suggests that the real value is only around 4.5%.

Full code to reproduce this error is in the starvz_iptw repository, but basically what I did is just extended current `st_time_aggregation` and its underlying functions to keep X and Y, loaded the first 1000 ms of the data, and then compared the 500ms-600ms period on X=2 & Y=2 as well as X=2 & Y=3:

```R
data <- data$State
data <- data[data$Start < 1000,]
dgg <- st_time_aggregation(data)

na.omit(data[data$X==0 & data$Y==2 & data$End>500 & data$Start<600, c("Value", "Start", "End", "Duration")])
na.omit(data[data$X==0 & data$Y==3 & data$End>500 & data$Start<600, c("Value", "Start", "End", "Duration")])
dgg[dgg$X==0 & dgg$Y==2 & dgg$End>500 & dgg$Start<600, c("Task", "Start", "End", "Value", "Duration")]
dgg[dgg$X==0 & dgg$Y==3 & dgg$End>500 & dgg$Start<600, c("Task", "Start", "End", "Value", "Duration")]
```

The output I am getting is:

```R
> na.omit(data[data$X==0 & data$Y==2 & data$End>500 & data$Start<600, c("Value", "Start", "End", "Duration")])
# A tibble: 4 x 4
  Value         Start   End Duration
  <chr>         <dbl> <dbl>    <dbl>
1 diffuse_relax  506.  507.     1.13
2 diffuse_relax  530.  531.     1.12
3 diffuse_relax  554.  555.     1.13
4 diffuse_relax  582.  583.     1.12
> na.omit(data[data$X==0 & data$Y==3 & data$End>500 & data$Start<600, c("Value", "Start", "End", "Duration")])
# A tibble: 4 x 4
  Value         Start   End Duration
  <chr>         <dbl> <dbl>    <dbl>
1 diffuse_relax  515.  516.     1.14
2 diffuse_relax  539.  540.     1.15
3 diffuse_relax  567.  568.     1.14
4 diffuse_relax  591.  592.     1.14
> dgg[dgg$X==0 & dgg$Y==2 & dgg$End>500 & dgg$Start<600, c("Task", "Start", "End", "Value", "Duration")]
# A tibble: 7 x 5
  Task            Start   End Value Duration
  <chr>           <dbl> <dbl> <dbl>    <dbl>
1 conserve_1        500   600 0          100
2 conserve_commit   500   600 0          100
3 conserve_relax    500   600 0          100
4 diffuse_relax     500   600 0.771      100
5 initial_state     500   600 0          100
6 macCormack_1      500   600 0          100
7 macCormack_2      500   600 0          100
> dgg[dgg$X==0 & dgg$Y==3 & dgg$End>500 & dgg$Start<600, c("Task", "Start", "End", "Value", "Duration")]
# A tibble: 7 x 5
  Task            Start   End Value Duration
  <chr>           <dbl> <dbl> <dbl>    <dbl>
1 conserve_1        500   600 0          100
2 conserve_commit   500   600 0          100
3 conserve_relax    500   600 0          100
4 diffuse_relax     500   600 0.409      100
5 initial_state     500   600 0          100
6 macCormack_1      500   600 0          100
7 macCormack_2      500   600 0          100
```

So first issue is that the output of the aggregated data doesnt seem to correspond to the raw data. Second strange thing is that aggregated data for two very similar input cases provides quite different outputs. 

Did anyone notice any strange behavior of the aggregation before? Are you sure that all previous plots and analysis used aggregation correctly? l hope that it is just me and I am doing something wrong here...

**Comment by llnns** [comment]
Hi Luka,

Just to clarify, with this merge, we can load StarVZ with only  `library(starvz)`. We don't need `source` anymore. Different from the CFD LabBook.

About the aggregation, the problem is that the aggregation's functions are misleading the  X and Y groups.

If i do a 
` data <- data[data$Start < 1000 & data$X==0 & data$Y==2,]`
And then execute the functions, I got the correct result:
```
1 conserve_1      500.  600. 0.         100.
2 conserve_relax  500.  600. 0.         100.
3 diffuse_relax   500.  600. 0.0450     100.
4 initial_state   500.  600. 0.         100.
```

I tried to incorporate the `group_by(..., X, Y)` inside the functions, but I was unsuccessful. Maybe @schnorr can help us.

**Comment by stanisic** [comment]
>  we can load StarVZ with only library(starvz). We don't need source anymore
Sure, I know...

Indeed, your explanation helped me realize how I need to change the aggregation. It needs to be done purely for X-Y, without ResourceID or similar, and then everything is fine (see CFD Labbbook for more details).

So all everything has been solved and I will close the issue.
